- hosts: all
  name: Adding new domain to instance
  gather_facts: no
  vars:
    website: "{{ fake_website }}"
    domain: "{{ domain_name }}"
  tasks:
    - block:
      - name: Create webroot directory
        ansible.builtin.file:
          path: /var/www/html/{{ domain }}
          state: directory
          owner: caddy
          group: caddy
          mode: '0744'
          
      - name: Archive the content of the template website
        archive:
          path: "../webserver/template_website/{{ website }}/*"
          dest: "../webserver/template_website/{{ website }}.tar.gz"
        delegate_to: localhost

      - name: Unarchive template website onto remote host
        ansible.builtin.unarchive:
          src: "../webserver/template_website/{{ website }}.tar.gz"
          dest: /var/www/html/{{ domain }}
          owner: caddy
          group: caddy

      - name: Remove local website template archive
        file: 
          path: "../webserver/template_website/{{ website }}.tar.gz"
          state: absent
        delegate_to: localhost

      - name: Upload new Caddyfile
        ansible.builtin.blockinfile:
          block: "{{ lookup('ansible.builtin.file', '../webserver/caddy/Caddyfile') }}"
          path: /opt/caddy/Caddyfile
          marker: "# {mark} {{ domain }}"
          prepend_newline: true
          backup: yes

      -  name: Create env file with the token
         ansible.builtin.copy:
          content: "DIGITALOCEAN_TOKEN={{ lookup('env', 'DIGITALOCEAN_TOKEN') }}"
          dest: /opt/caddy/.env
          owner: root
          group: root
          mode: '0600'

      - name: Restart caddy service
        ansible.builtin.systemd_service:
          name: caddy
          state: reloaded
      
      - name: Remove the token from the env file
        ansible.builtin.lineinfile:
          path: /opt/caddy/.env
          regexp: '^DIGITALOCEAN_TOKEN'
          state: absent